services:
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    ports:
      - "5232:5232"
    volumes:
      - ./radicale/data:/data
      - ./radicale/config:/config
    environment:
      - RADICALE_CONFIG=/config/config
    restart: unless-stopped
